### ISSUE TITLE
Long pathnames + filename unable to load from Recent/History

### ISSUE THREAD

**Issue by DiscostewSM** [averne/SwitchWave#2]
I believe there is a string length limitation in effect that will cause any entry whose path + filename that is greater than 255-256 characters gets truncated and/or has junk at the end of it when added to the Recent/History list. This was tested when connecting to my Synology NAS via NFS to access my Plex Media folder, where I have directories within directories for my media for organization purposes.

**Comment by DiscostewSM** [comment]
The "history.txt" file made for the Recent list is showing the complete full path + filename for each entry. So doing things like adding to the list and reading/writing to the filesystem seem fine.

**Comment by averne** [comment]
Fixed, attached is a build if you want to try it.
I haven't been able to reproduced the issue with paths containing #-symbols that you reported on gbatemp, though. Can you double check the conditions for it to happen?
[SwitchWave-1.0.0-014c84b.zip](https://github.com/user-attachments/files/17511472/SwitchWave-1.0.0-014c84b.zip)

**Comment by DiscostewSM** [comment]
The long pathnames seem fixed with your changes, so thank you.

As for entering something like "#recycle" from a shared folder via NFS on my NAS that caused it to lock up the entire system, I'm unfortunately unable to replicate it because since then, I had emptied that directory and disabled it. I had re-enabled it just now and deleted some stuff for some content to exist in it like before, but even with the initial build of your program, it's not causing a lockup like before. Thing is, I recall there was only one subdirectory immediately under the "#recycle" directory, and that was named "Videos" as I had it structured for my Plex Media Server. In it, it had "Movies" and "TV Shows" subdirectories, and then individual movie and tv show directories in those. Nothing else. Maybe there was some hidden file/folder causing issues? In any case, I can't replicate it right now.

If it ever crops up again, I'll make sure to report it.

**Comment by averne** [comment]
I tried to insert #s in directory and file names, which didn't seem to cause any issue. I'll give it some more tries, but it might have been something else.
Don't hesitate to open an issue if you run into it again.
